name: 2dgh
channels:
  - pytorch3d
  - pytorch
  - iopath
  - fvcore
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.2.2
  - pillow=10.2.0
  - pip=23.3.1
  - python=3.8.18
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.9.0
  - pip:
    - open3d==0.18.0
    - mediapy==1.1.2
    - lpips==0.1.4
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - matplotlib==3.7.5
    - black==24.4.2
    - usort==1.0.8.post1
    - plotly==5.22.0
    - opencv-python==4.10.0.84
    - imageio==2.34.2
    - flake8==7.1.0
    - flake8-bugbear==24.4.26
    - flake8-comprehensions==3.15.0
    - submodules/diff-ges-surfel-rasterization
    - submodules/diff_gh_surfel_rasterization
    - submodules/diff-surfel-rasterization-original
    - submodules/simple-knn